In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
dataset= pd.read_csv("weather_classification_data.csv")
dataset.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy

In [24]:
dataset.isnull().sum() #there is no any null value.so i can perform encoding here

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility (km)         0
Location                0
Weather Type            0
dtype: int64

In [25]:
#one hot incoding chai specific answer vako ma use hunxa.L
#like true false,male female wala data ma .so esma ma season,type ,cloud cover haru ma one hot encoding perform garna milxa.

In [26]:
#seperating the rows , column you want to perform one hot encoding
en_data= dataset[["Season","Weather Type"]]
en_data.head()

   Season Weather Type
0  Winter        Rainy
1  Spring       Cloudy
2  Spring        Sunny
3  Spring        Sunny
4  Winter        Rainy

In [27]:
#we use get_dummies method of pandas for one hot encoding
pd.get_dummies(en_data).head()

,Season_Autumn,Season_Spring,Season_Summer,Season_Winter,Weather Type_Cloudy,Weather Type_Rainy,Weather Type_Snowy,Weather Type_Sunny
0,False,False,False,True,False,True,False,False
1,False,True,False,False,True,False,False,False
2,False,True,False,False,False,False,False,True
3,False,True,False,False,False,False,False,True
4,False,False,False,True,False,True,False,False

In [28]:
#but we do it from sklearn

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
ohe= OneHotEncoder()
ar=ohe.fit_transform(en_data).toarray()

In [32]:
pd.DataFrame(ar,columns=["Season_Autumn","Season_Spring","Season_Summer","Season_Winter","Weather Type_Cloudy","Weather Type_Rainy",
                          "Weather Type_Snowy","Weather Type_Sunny"	]).head()

,Season_Autumn,Season_Spring,Season_Summer,Season_Winter,Weather Type_Cloudy,Weather Type_Rainy,Weather Type_Snowy,Weather Type_Sunny
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0