In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
data={
    "name":["Samarpan","Samyog","Aditya","Samarpan"],
    "subject":["Computer Science","Computer Science","Business Administration","Computer Science"]
    }
data

{'name': ['Samarpan', 'Samyog', 'Aditya', 'Samarpan'],
 'subject': ['Computer Science',
  'Computer Science',
  'Business Administration',
  'Computer Science']}

In [16]:
df=pd.DataFrame(data)
df

       name                  subject
0  Samarpan         Computer Science
1    Samyog         Computer Science
2    Aditya  Business Administration
3  Samarpan         Computer Science

In [17]:
df["duplicates"]=df.duplicated()
df

       name                  subject  duplicates
0  Samarpan         Computer Science       False
1    Samyog         Computer Science       False
2    Aditya  Business Administration       False
3  Samarpan         Computer Science        True

In [18]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [19]:
data=pd.DataFrame(data)
data

       name                  subject
0  Samarpan         Computer Science
1    Samyog         Computer Science
2    Aditya  Business Administration
3  Samarpan         Computer Science

In [23]:
data.drop_duplicates(keep="first",inplace=True)
data

       name                  subject
0  Samarpan         Computer Science
1    Samyog         Computer Science
2    Aditya  Business Administration

In [25]:
dataset=pd.read_csv("File.csv")
dataset.head()

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,NaN,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11

In [27]:
dataset.duplicated().sum()

0